In [ ]:
#Load the dataset and only selecting the numerical features for example purposes
titanic = sns.load_dataset('titanic')[['survived', 'pclass', 'age', 'parch', 'sibsp', 'fare']].dropna()
X = titanic.drop('survived', axis = 1)
y = titanic['survived']

In [ ]:
X

     pclass   age  parch  sibsp     fare
0         3  22.0      0      1   7.2500
1         1  38.0      0      1  71.2833
2         3  26.0      0      0   7.9250
3         1  35.0      0      1  53.1000
4         3  35.0      0      0   8.0500
..      ...   ...    ...    ...      ...
885       3  39.0      5      0  29.1250
886       2  27.0      0      0  13.0000
887       1  19.0      0      0  30.0000
889       1  26.0      0      0  30.0000
890       3  32.0      0      0   7.7500

[714 rows x 5 columns]

In [ ]:
y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: survived, Length: 714, dtype: int64

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

In [ ]:

rfe_selector = RFE(estimator=RandomForestClassifier(),n_features_to_select = 2, step = 1)
m=rfe_selector.fit(X, y)
X.columns[m.get_support()]
print("Num Features: %s" % (m.n_features_))
print("Selected Features: %s" % (m.support_))
print("Feature Ranking: %s" % (m.ranking_))

Num Features: 2
Selected Features: [False  True False False  True]
Feature Ranking: [2 1 4 3 1]

In [ ]:
X.loc[:, m.support_].columns

Index(['age', 'fare'], dtype='object')

In [ ]:
SFM = SelectFromModel(estimator=RandomForestClassifier()).fit(X, y)
s=SFM.fit(X, y)

In [ ]:

n_features = s.transform(X).shape[1]

n_features

2

In [ ]:
feature_idx = s.get_support()
feature_name = X.columns[feature_idx]
feature_name

Index(['age', 'fare'], dtype='object')

In [ ]:
from sklearn.feature_selection import RFECV


rfecv = RFECV(
    estimator=RandomForestClassifier(),
    min_features_to_select=2,
    step=5,
    n_jobs=-1,
    scoring="r2",
    cv=5,
)

m= rfecv.fit(X, y)

In [ ]:
X.columns[rfecv.support_]

Index(['pclass', 'age', 'parch', 'sibsp', 'fare'], dtype='object')